### Criar usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "nome": "João da Silva",
  "email": "txaaaaa@example.com",
  "senha_hash": "senhaSegura123",
  "foto_url": "https://example.com/foto.jpg",
  "papel": "Scrum Master",
  "ativo": true,
  "score": 88
}

### Buscar todos os usuários
GET http://localhost:3000/users

### Buscar usuário por ID
GET http://localhost:3000/users/6823804ed7aa7e4e1e34de80

### Atualizar usuário
PATCH http://localhost:3000/users/6812687a03f3a271c0b95dec
Content-Type: application/json

{
  "nome": "João da Silva Atualizado",
  "papel": "Desenvolvedor",
  "score": 92
}

### Associar usuário ao projeto
# Substitua USER_ID e PROJECT_ID pelos IDs reais retornados das requisições acima
POST http://localhost:3000/users/68120b9e27268e6965f0714a/assign-to-project/6810d7b6bda0b83953c0261f

### Remover usuário
DELETE http://localhost:3000/users/{{userId}}
