### Criar projeto
POST http://localhost:3000/project
Content-Type: application/json

{
  "nome": "Chronos",
  "descricao": "Sistema de gerenciamento ágil",
  "data_inicio": "2025-05-01T00:00:00.000Z",
  "data_fim": "2025-12-31T00:00:00.000Z",
  "status": "ativo"
}

###

### Listar todos os projetos
GET http://localhost:3000/project

###

### Buscar projeto por ID
GET http://localhost:3000/project/6810d6ca94c434a8d673442c

###

### Atualizar projeto
PATCH http://localhost:3000/project/6810d6ca94c434a8d673442c
Content-Type: application/json

{
  "descricao": "Sistema atualizado com novas funcionalidades",
  "status": "em progresso"
}

###

### Deletar projeto
DELETE http://localhost:3000/project/{{projectId}}
